name: IncludeOS CI
on: [push]

jobs:
  ubuntu-build:
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2.0.0
    - name: prepare build system
      run: apt-get update && apt-get -y python3-pip python3-dev git cmake clang-6.0 gcc nasm make qemu && apt-get clean
    - name: Register layout
      run: conan editable add . includeos/$(conan inspect -a version . | cut -d " " -f 2)@includeos/latest --layout=etc/layout.txt
    - name: List Editable targets
      run: conan editable list
    - name: conan install 
      run:  conan install -if build . -pr clang-6.0-linux-x86_64
    - name: conan
      run: conan build -bf build .
    - name: cd build && make
    
      
