name: IncludeOS CI
on: [push]

jobs:
  ubuntu-build:
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2.0.0
    - name: Setup IncludeOS Build deps
      run: sudo apt-get update && sudo apt-get install -y --no-install-recommends python3-pip python3-setuptools python3-wheel python3-dev git cmake clang-6.0 gcc nasm make qemu && sudo pip3 install conan psutil jsonschema 
    - name: Conan install
      run: conan config install https://github.com/includeos/conan_config.git
    - name: Register layout
#      run: conan editable add . includeos/$(conan inspect -a version . | cut -d " " -f 2)@includeos/latest --layout=etc/layout.txt'
      run: conan editable add . includeos/0.0.0@includeos/latest --layout=etc/layout.txt
    - name: List Editable targets
      run: conan editable list
    - name: conan install 
      run:  conan install -if build . -pr clang-6.0-linux-x86_64
    - name: conan
      run: conan build -bf build .
    - name: make 
      run: cd build && make

      
