name: IncludeOS CI
on: [push]

jobs:
  ubuntu-build:
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2.0.0
    - name: Setup C++ environment
      uses: kurocha/setup-cpp@v1    
    - name: Register layout
      run: conan editable add . includeos/$(conan inspect -a version . | cut -d " " -f 2)@includeos/latest --layout=etc/layout.txt
    - name: List Editable targets
      run: conan editable list
    - name: conan install 
      run:  conan install -if build . -pr clang-6.0-linux-x86_64
    - name: conan
      run: conan build -bf build .
    - name: make 
      run: cd build && make

      
